//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAVRAMOBS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAVRAMOBS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ogrenciweb.kavram.edu.tr/oibs/ogrenci/__oplgnsnstart.
        /// </summary>
        internal static string captchaSoundUrl {
            get {
                return ResourceManager.GetString("captchaSoundUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ogrenciweb.kavram.edu.tr/oibs/captcha/CaptchaImg.aspx.
        /// </summary>
        internal static string captchaUrl {
            get {
                return ResourceManager.GetString("captchaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAAx4V-G1Q:APA91bEw1x_KUaIG-HVbFh--eOFmKa8I6gFnCaA25i7b54tf5P820DkMGrWd1D8AacrKSACA39ul6bkkOH_wkzOiFaoHmR1RTb5pSev3j_5VgebghYEPeT6cskhQQw4tEAtGkKRGXocK.
        /// </summary>
        internal static string firebase_key {
            get {
                return ResourceManager.GetString("firebase_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 856938126164.
        /// </summary>
        internal static string firebase_sender_id {
            get {
                return ResourceManager.GetString("firebase_sender_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ogrenciweb.kavram.edu.tr/oibs/ogrenci/login.aspx.
        /// </summary>
        internal static string loginUrl {
            get {
                return ResourceManager.GetString("loginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.logsnag.com/v1/log.
        /// </summary>
        internal static string logsnagUrl {
            get {
                return ResourceManager.GetString("logsnagUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ogrenciweb.kavram.edu.tr/oibs/ogrenci/start.aspx?gkm=0018344203777037700377073672034184332913780533336344803425238792389363668433237355603742738384.
        /// </summary>
        internal static string mailReferrerUrl {
            get {
                return ResourceManager.GetString("mailReferrerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ogrenciweb.kavram.edu.tr/oibs/ogrenci/start.aspx?gkm=002337693376793664833324355053111437322387763223033336389603850434396378193111438640376793661833303353053734321492150.
        /// </summary>
        internal static string mailUrl {
            get {
                return ResourceManager.GetString("mailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{&quot;project&quot;:&quot;{0}&quot;,&quot;channel&quot;:&quot;{1}&quot;,&quot;event&quot;:&quot;{2}&quot;,&quot;description&quot;:&quot;{3}&quot;,&quot;icon&quot;:&quot;{4}&quot;,&quot;notify&quot;:{5}}}.
        /// </summary>
        internal static string notificationFormat {
            get {
                return ResourceManager.GetString("notificationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   █▀▀▀▀▀█ ▀▄█▄█▀█ ▄ █▀▀▀▀▀█
        ///  █ ███ █ ███ ▄█▀█▄ █ ███ █
        ///  █ ▀▀▀ █ ▀ ▄█▀▀█▀  █ ▀▀▀ █
        ///  ▀▀▀▀▀▀▀ ▀ █ █ █ ▀ ▀▀▀▀▀▀▀
        ///  ▀█▀▀▄ ▀ █ █▀▄ █  ▀ ▄▀▀▀▄▀
        ///  █▄▀█ █▀▀ █████▄  ▄  ▀▄▄  
        ///  ▀█▄██ ▀ ██▀▀▀▀██▄▀███ ▀▀█
        ///  ▄▀▄▀█ ▀ ▄▀  ▄▀█ █▄ ▄█ ▀▀▄
        ///    ▀   ▀▀█▀▀███ ▄█▀▀▀█▀█▀█
        ///  █▀▀▀▀▀█  ▀ ▄▀▀▄ █ ▀ █ ▀▀█
        ///  █ ███ █ ▄█▄▄▀▄  ▀██▀██▄▄█
        ///  █ ▀▀▀ █ █▄▄▀▀█ ▀▀▄▀ █ █▀ 
        ///  ▀▀▀▀▀▀▀ ▀▀  ▀▀▀▀  ▀▀▀▀▀▀▀.
        /// </summary>
        internal static string qrCode {
            get {
                return ResourceManager.GetString("qrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function strnew(r){var o=r,C=&quot;&quot;,e=&quot;&quot;,a=makeid(),d=makeid(),m=makeid(),n=makeid(),t=makeid(),h=makeid(),f=makeid(),g=makeid(),S=makeid(),c=makeid(),l=makeid(),p=makeid(),k=makeid(),s=makeid(),A=makeid(),u=makeid(),w=makeid(),y=makeid(),b=makeid(),v=makeid(),M=makeid(),j=makeid(),q=makeid(),x=makeid(),z=makeid(),B=makeid(),D=makeid(),E=makeid(),F=makeid(),G=makeid(),H=makeid(),I=makeid(),J=makeid(),K=makeid(),L=makeid(),N=makeid(),O=makeid(),P=makeid(),Q=makeid(),R=makeid(),T=makeid(),U=makeid(),V=makeid(),W= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
    }
}
